export GITHUB_REPOSITORY_URL="https://github.com/hyamine/openwrt-build-actions"
export GITHUB_REPOSITORY="hyamine/openwrt-build-actions"
export GITHUB_REPOSITORY_REFNAME="openwrt-23.05"
export GITHUB_REPOSITORY_REF="refs/heads/openwrt-23.05"
export GITHUB_ACTOR="hyamine"
export GITHUB_WORKFLOW="Openwrt_lxc编译"
export REPO_TOKEN=""
export TELEGRAM_CHAT_ID=""
export TELEGRAM_BOT_TOKEN=""
export PUSH_PLUS_TOKEN=""
export TZ="Asia/Shanghai"

export INPUTS_SOURCE_BRANCH="openwrt-23.05"
export INPUTS_CONFIG_FILE="x86_64"
export INPUTS_FIRMWARE_TYPE="lxc"
export INPUTS_BIOS_MODE="uefi"        
export INPUTS_NOTICE_TYPE="false"
export INPUTS_ENABLE_SSH="false"
export INPUTS_UPLOAD_RELEASE="false"
export INPUTS_UPLOAD_FIRMWARE="false"
export INPUTS_UPLOAD_CONFIG="false"
export INPUTS_ENABLE_CCACHE="false"

export MATRIX_TARGET="Openwrt_lxc"
